### ISSUE TITLE
Support adding entries to Pod /etc/hosts with HostAliases

### ISSUE THREAD

**Issue by AminShaarawe** [simplify9/Infolink#52]
Support adding entries to Pod /etc/hosts with HostAliases

values.yaml
```
# hostAliases allow additional DNS entries to be injected directly into pods /etc/hosts file.
# Override hostAliases in infolink deployment values file
hostAliases:
  - ip: 192.168.1.100
    hostNames:
      - my.host.com
      - another.host.net
  - ip: 192.168.1.101
    hostNames:
      - your.host.com
```
